13:59:02.825 [error] #PID<0.911.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.909.0>, stream id 1) terminated
Server: 127.0.0.1:4005 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) no "home" json template defined for BacProWeb.PageJSON  (the module does not exist)
        (phoenix_template 1.0.4) lib/phoenix/template.ex:248: Phoenix.Template.render_with_fallback/4
        (phoenix_template 1.0.4) lib/phoenix/template.ex:126: Phoenix.Template.render_to_iodata/4
        (phoenix 1.7.11) lib/phoenix/controller.ex:1008: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.11) lib/phoenix/controller.ex:974: Phoenix.Controller.render_and_send/4
        (bac_pro 0.1.0) lib/bac_pro_web/controllers/page_controller.ex:1: BacProWeb.PageController.action/2
        (bac_pro 0.1.0) lib/bac_pro_web/controllers/page_controller.ex:1: BacProWeb.PageController.phoenix_controller_pipeline/2
        (phoenix 1.7.11) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
        (bac_pro 0.1.0) lib/bac_pro_web/endpoint.ex:1: BacProWeb.Endpoint.plug_builder_call/2
        (bac_pro 0.1.0) deps/plug/lib/plug/debugger.ex:136: BacProWeb.Endpoint."call (overridable 3)"/2
        (bac_pro 0.1.0) lib/bac_pro_web/endpoint.ex:1: BacProWeb.Endpoint.call/2
        (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.7.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
13:59:55.142 [error] Customer validator Job id: 1 | Job attempted at: ~U[2024-02-04 11:59:55.123783Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
13:59:55.151 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
14:00:12.869 [error] Customer validator Job id: 1 | Job attempted at: ~U[2024-02-04 12:00:12.861036Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
14:00:12.873 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
14:00:13.887 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:22:38.245 [error] Customer validator Job id: 3 | Job attempted at: ~U[2024-02-04 12:22:38.212555Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
14:22:38.250 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
14:22:56.190 [error] Customer validator Job id: 3 | Job attempted at: ~U[2024-02-04 12:22:56.145026Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
14:22:56.196 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
14:23:01.420 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:23:02.431 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:23:17.559 [error] [value: #Ecto.Changeset<action: :insert, changes: %{email: "hata22@gmail.com", dateOfBirth: "2000-10-22", idNumber: "5811111121211", phoneNumber: "0727941660"}, errors: [firstname: {"can't be blank", [validation: :required]}, lastname: {"can't be blank", [validation: :required]}], data: #BacPro.Customers.Customer<>, valid?: false>, protocol: String.Chars, description: "", __struct__: Protocol.UndefinedError, __exception__: true]
14:23:34.637 [error] [value: #Ecto.Changeset<action: :insert, changes: %{email: "hata22@gmail.com", dateOfBirth: "2000-10-22", idNumber: "5811111121211", phoneNumber: "0727941660"}, errors: [firstname: {"can't be blank", [validation: :required]}, lastname: {"can't be blank", [validation: :required]}], data: #BacPro.Customers.Customer<>, valid?: false>, protocol: String.Chars, description: "", __struct__: Protocol.UndefinedError, __exception__: true]
14:23:54.871 [error] [value: #Ecto.Changeset<action: :insert, changes: %{email: "hata22@gmail.com", dateOfBirth: "2000-10-22", idNumber: "5811111121211", phoneNumber: "0727941660"}, errors: [firstname: {"can't be blank", [validation: :required]}, lastname: {"can't be blank", [validation: :required]}], data: #BacPro.Customers.Customer<>, valid?: false>, protocol: String.Chars, description: "", __struct__: Protocol.UndefinedError, __exception__: true]
14:23:55.843 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:24:16.986 [error] [value: #Ecto.Changeset<action: :insert, changes: %{email: "hata22@gmail.com", dateOfBirth: "2000-10-22", idNumber: "5811111121211", phoneNumber: "0727941660", firstname: "Hataluli"}, errors: [lastname: {"can't be blank", [validation: :required]}], data: #BacPro.Customers.Customer<>, valid?: false>, protocol: String.Chars, description: "", __struct__: Protocol.UndefinedError, __exception__: true]
14:24:35.532 [error] [value: #Ecto.Changeset<action: :insert, changes: %{email: "hata22@gmail.com", dateOfBirth: "2000-10-22", idNumber: "5811111121211", phoneNumber: "0727941660", firstname: "Hataluli"}, errors: [lastname: {"can't be blank", [validation: :required]}], data: #BacPro.Customers.Customer<>, valid?: false>, protocol: String.Chars, description: "", __struct__: Protocol.UndefinedError, __exception__: true]
14:24:54.645 [error] [value: #Ecto.Changeset<action: :insert, changes: %{email: "hata22@gmail.com", dateOfBirth: "2000-10-22", idNumber: "5811111121211", phoneNumber: "0727941660", firstname: "Hataluli"}, errors: [lastname: {"can't be blank", [validation: :required]}], data: #BacPro.Customers.Customer<>, valid?: false>, protocol: String.Chars, description: "", __struct__: Protocol.UndefinedError, __exception__: true]
14:24:55.632 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:28:05.561 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: \"3364371561572\"}, errors: [account_type: {\"can't be blank\", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: "3364371561572"}, errors: [account_type: {"can't be blank", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:28:22.615 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: \"3364371561572\"}, errors: [account_type: {\"can't be blank\", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: "3364371561572"}, errors: [account_type: {"can't be blank", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:28:42.759 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: \"3364371561572\"}, errors: [account_type: {\"can't be blank\", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: "3364371561572"}, errors: [account_type: {"can't be blank", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:29:06.848 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: \"3364371561572\"}, errors: [account_type: {\"can't be blank\", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{balance: 1500.0, account_number: "3364371561572"}, errors: [account_type: {"can't be blank", [validation: :required]}], data: #BacPro.Accounts.Account<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:44:55.106 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420003218593092325\", cvv: \"325\"}, errors: [card_status: {\"can't be blank\", [validation: :required]}, expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420003218593092325", cvv: "325"}, errors: [card_status: {"can't be blank", [validation: :required]}, expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:45:12.171 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420001344542297544\", cvv: \"544\"}, errors: [card_status: {\"can't be blank\", [validation: :required]}, expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420001344542297544", cvv: "544"}, errors: [card_status: {"can't be blank", [validation: :required]}, expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:45:31.294 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420003390487838129\", cvv: \"129\"}, errors: [card_status: {\"can't be blank\", [validation: :required]}, expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420003390487838129", cvv: "129"}, errors: [card_status: {"can't be blank", [validation: :required]}, expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:46:44.969 [error] Customer creation Job id: 9 | Job attempted at: ~U[2024-02-04 12:46:43.951766Z]| Job state: "executing" | Job queue: "events" | Job queue: 1 | Error : Email already exists.
14:46:44.972 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:error, \"Email already exists.\"}", reason: {:error, "Email already exists."}, __struct__: Oban.PerformError, __exception__: true]
14:47:03.762 [error] Customer creation Job id: 9 | Job attempted at: ~U[2024-02-04 12:47:03.742839Z]| Job state: "executing" | Job queue: "events" | Job queue: 2 | Error : Email already exists.
14:47:03.770 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:error, \"Email already exists.\"}", reason: {:error, "Email already exists."}, __struct__: Oban.PerformError, __exception__: true]
14:47:07.391 [error] [Oban.Pro.Worker] hook error: ** (UndefinedFunctionError) function BacPro.Workershook.ErrorHook.after_process/2 is undefined or private
    (bac_pro 0.1.0) BacPro.Workershook.ErrorHook.after_process(:complete, %Oban.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">, id: 12, state: "executing", queue: "valid", worker: "BacPro.Workers.CustomerValidatorWorkerPro", args: %{"customer" => %{"dateOfBirth" => "2000-10-22", "email" => "hata11@gmail.com", "firstname" => "Hataluli", "idNumber" => "5811111121211", "lastname" => "Randima", "phoneNumber" => "0727941660"}}, meta: %{"deps" => [], "name" => "a", "workflow_id" => "018d7428-7e25-7890-a51a-057b73c18d08"}, tags: ["customer", "validation"], errors: [], attempt: 1, attempted_by: ["DESKTOP-57HBI13", "018d7418-b5d7-7911-89ba-1ea679bbc27d"], max_attempts: 2, priority: 3, attempted_at: ~U[2024-02-04 12:47:07.348795Z], cancelled_at: nil, completed_at: nil, discarded_at: nil, inserted_at: ~U[2024-02-04 12:47:07.328033Z], scheduled_at: ~U[2024-02-04 12:47:07.328033Z], conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Engines.Smart, get_dynamic_repo: nil, insert_trigger: true, log: false, name: Oban, node: "DESKTOP-57HBI13", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Pro.Plugins.DynamicQueues, [queues: [default: 10, valid: 12, scheduled: 10, crato: 25, events: 20]]}, {Oban.Pro.Plugins.DynamicPruner, [mode: {:max_age, {2, :days}}]}], prefix: "public", queues: [], repo: BacPro.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, conflict?: false, replace: nil, unique: nil, unsaved_error: nil})
    (elixir 1.16.0-rc.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (oban_pro 1.3.3) lib/oban/pro/stages/hooks.ex:68: Oban.Pro.Stages.Hooks.handle_event/4
    (telemetry 1.2.1) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/telemetry/src/telemetry.erl:160: anonymous fn/4 in :telemetry.execute/3
    (stdlib 5.1.1) lists.erl:1686: :lists.foreach_1/2
    (oban 2.17.3) lib/oban/queue/executor.ex:282: Oban.Queue.Executor.emit_event/1
    (oban 2.17.3) lib/oban/queue/executor.ex:81: anonymous fn/1 in Oban.Queue.Executor.call/1
    (oban 2.17.3) lib/oban/backoff.ex:104: Oban.Backoff.with_retry/3
    (elixir 1.16.0-rc.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.16.0-rc.0) lib/task/supervised.ex:36: Task.Supervised.reply/4

14:47:10.409 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420009773307270563\", cvv: \"563\"}, errors: [expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420009773307270563", cvv: "563"}, errors: [expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:47:22.950 [error] Customer creation Job id: 9 | Job attempted at: ~U[2024-02-04 12:47:22.930761Z]| Job state: "executing" | Job queue: "events" | Job queue: 3 | Error : Email already exists.
14:47:22.959 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:error, \"Email already exists.\"}", reason: {:error, "Email already exists."}, __struct__: Oban.PerformError, __exception__: true]
14:47:23.957 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:47:28.015 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:47:28.040 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420002159655455917\", cvv: \"917\"}, errors: [expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420002159655455917", cvv: "917"}, errors: [expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:47:47.100 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420003445660859507\", cvv: \"507\"}, errors: [expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420003445660859507", cvv: "507"}, errors: [expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:48:11.017 [error] Customer creation Job id: 17 | Job attempted at: ~U[2024-02-04 12:48:09.995784Z]| Job state: "executing" | Job queue: "events" | Job queue: 1 | Error : Email already exists.
14:48:11.021 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:error, \"Email already exists.\"}", reason: {:error, "Email already exists."}, __struct__: Oban.PerformError, __exception__: true]
14:48:28.305 [error] Customer creation Job id: 17 | Job attempted at: ~U[2024-02-04 12:48:28.294952Z]| Job state: "executing" | Job queue: "events" | Job queue: 2 | Error : Email already exists.
14:48:28.309 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:error, \"Email already exists.\"}", reason: {:error, "Email already exists."}, __struct__: Oban.PerformError, __exception__: true]
14:48:41.927 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420009393820219054\", cvv: \"054\"}, errors: [expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420009393820219054", cvv: "054"}, errors: [expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:48:47.440 [error] Customer creation Job id: 17 | Job attempted at: ~U[2024-02-04 12:48:47.432280Z]| Job state: "executing" | Job queue: "events" | Job queue: 3 | Error : Email already exists.
14:48:47.443 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:error, \"Email already exists.\"}", reason: {:error, "Email already exists."}, __struct__: Oban.PerformError, __exception__: true]
14:48:52.464 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:48:53.470 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
14:48:59.514 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420007440542455875\", cvv: \"875\"}, errors: [expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420007440542455875", cvv: "875"}, errors: [expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
14:49:18.611 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: \"67420009697018258464\", cvv: \"464\"}, errors: [expiry_date: {\"is invalid\", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}", reason: {:error, #Ecto.Changeset<action: :insert, changes: %{card_number: "67420009697018258464", cvv: "464"}, errors: [expiry_date: {"is invalid", [type: :date, validation: :cast]}], data: #BacPro.Accounts.Card<>, valid?: false>}, __struct__: Oban.PerformError, __exception__: true]
16:55:49.780 [error] [Oban.Pro.Worker] hook error: ** (UndefinedFunctionError) function BacPro.Workershook.ErrorHook.after_process/2 is undefined or private
    (bac_pro 0.1.0) BacPro.Workershook.ErrorHook.after_process(:error, %Oban.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">, id: 10, state: "executing", queue: "valid", worker: "BacPro.Workers.ValidCardWorkerPro", args: %{"account_id" => "060a632d-b977-4190-9b9d-0fc8dd47e7de", "amount_dep" => 120, "amount_with" => 200}, meta: %{"deps" => [], "name" => "aa", "recorded" => true, "workflow_id" => "018d749e-53ac-72ef-82ad-76822de582c6"}, tags: ["account", "validation"], errors: [], attempt: 1, attempted_by: ["DESKTOP-57HBI13", "018d742d-0e3c-781a-9f75-f36da4ed6195"], max_attempts: 3, priority: 3, attempted_at: ~U[2024-02-04 14:55:49.723204Z], cancelled_at: nil, completed_at: nil, discarded_at: nil, inserted_at: ~U[2024-02-04 14:55:49.690386Z], scheduled_at: ~U[2024-02-04 14:55:49.690386Z], conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Engines.Smart, get_dynamic_repo: nil, insert_trigger: true, log: false, name: Oban, node: "DESKTOP-57HBI13", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Pro.Plugins.DynamicQueues, [queues: [default: 10, valid: 12, scheduled: 10, crato: 25, events: 20]]}, {Oban.Pro.Plugins.DynamicPruner, [mode: {:max_age, {2, :days}}]}], prefix: "public", queues: [], repo: BacPro.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, conflict?: false, replace: nil, unique: nil, unsaved_error: %{reason: %Protocol.UndefinedError{protocol: Ecto.Queryable, value: Account, description: "the given module does not exist"}, stacktrace: [{Ecto.Queryable.Atom, :to_query, 1, [file: ~c"lib/ecto/queryable.ex", line: 41]}, {Ecto.Repo.Queryable, :query_for_get, 2, [file: ~c"lib/ecto/repo/queryable.ex", line: 472]}, {Ecto.Repo.Queryable, :get, 4, [file: ~c"lib/ecto/repo/queryable.ex", line: 69]}, {BacPro.Workers.ValidCardWorkerPro, :get_account_struct_v2, 1, [file: ~c"lib/bac_pro/workers/valid_card_worker_pro.ex", line: 41]}, {BacPro.Workers.ValidCardWorkerPro, :process, 1, [file: ~c"lib/bac_pro/workers/valid_card_worker_pro.ex", line: 22]}, {BacPro.Workers.ValidCardWorkerPro, :perform, 1, [file: ~c"deps/oban_pro/lib/oban/pro/workers/workflow.ex", line: 648]}, {Oban.Queue.Executor, :perform, 1, [file: ~c"lib/oban/queue/executor.ex", line: 129]}, {Oban.Queue.Executor, :call, 1, [file: ~c"lib/oban/queue/executor.ex", line: 74]}, {Task.Supervised, :invoke_mfa, 2, [file: ~c"lib/task/supervised.ex", line: 101]}, {Task.Supervised, :reply, 4, [file: ~c"lib/task/supervised.ex", line: 36]}], kind: :error}})
    (elixir 1.16.0-rc.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (oban_pro 1.3.3) lib/oban/pro/stages/hooks.ex:68: Oban.Pro.Stages.Hooks.handle_event/4
    (telemetry 1.2.1) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/telemetry/src/telemetry.erl:160: anonymous fn/4 in :telemetry.execute/3
    (stdlib 5.1.1) lists.erl:1686: :lists.foreach_1/2
    (oban 2.17.3) lib/oban/queue/executor.ex:266: Oban.Queue.Executor.emit_event/1
    (oban 2.17.3) lib/oban/queue/executor.ex:81: anonymous fn/1 in Oban.Queue.Executor.call/1
    (oban 2.17.3) lib/oban/backoff.ex:104: Oban.Backoff.with_retry/3
    (elixir 1.16.0-rc.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.16.0-rc.0) lib/task/supervised.ex:36: Task.Supervised.reply/4

16:56:03.695 [error] [value: Account, protocol: Ecto.Queryable, description: "the given module does not exist", __struct__: Protocol.UndefinedError, __exception__: true]
16:56:07.571 [error] [value: Account, protocol: Ecto.Queryable, description: "the given module does not exist", __struct__: Protocol.UndefinedError, __exception__: true]
16:56:22.662 [error] [value: Account, protocol: Ecto.Queryable, description: "the given module does not exist", __struct__: Protocol.UndefinedError, __exception__: true]
16:56:26.694 [error] [value: Account, protocol: Ecto.Queryable, description: "the given module does not exist", __struct__: Protocol.UndefinedError, __exception__: true]
16:56:27.724 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:56:41.804 [error] [value: Account, protocol: Ecto.Queryable, description: "the given module does not exist", __struct__: Protocol.UndefinedError, __exception__: true]
16:56:42.803 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:58:28.287 [error] [message: "lib/bac_pro/workers/withdrawal_worker_pro.ex:78: field `account_id` in `where` does not exist in schema BacPro.Accounts.Account in query:\n\nfrom a0 in BacPro.Accounts.Account,\n  where: a0.account_id == ^\"060a632d-b977-4190-9b9d-0fc8dd47e7de\",\n  update: [set: [balance: ^1300.0]],\n  select: a0\n\nDid you mean one of: \n\n      * `account_type`\n      * `account_status`\n      * `account_number`\n", __struct__: Ecto.QueryError, __exception__: true]
16:58:46.435 [error] [message: "lib/bac_pro/workers/withdrawal_worker_pro.ex:78: field `account_id` in `where` does not exist in schema BacPro.Accounts.Account in query:\n\nfrom a0 in BacPro.Accounts.Account,\n  where: a0.account_id == ^\"060a632d-b977-4190-9b9d-0fc8dd47e7de\",\n  update: [set: [balance: ^1300.0]],\n  select: a0\n\nDid you mean one of: \n\n      * `account_type`\n      * `account_status`\n      * `account_number`\n", __struct__: Ecto.QueryError, __exception__: true]
16:59:06.530 [error] [message: "lib/bac_pro/workers/withdrawal_worker_pro.ex:78: field `account_id` in `where` does not exist in schema BacPro.Accounts.Account in query:\n\nfrom a0 in BacPro.Accounts.Account,\n  where: a0.account_id == ^\"060a632d-b977-4190-9b9d-0fc8dd47e7de\",\n  update: [set: [balance: ^1300.0]],\n  select: a0\n\nDid you mean one of: \n\n      * `account_type`\n      * `account_status`\n      * `account_number`\n", __struct__: Ecto.QueryError, __exception__: true]
16:59:30.676 [error] [message: "lib/bac_pro/workers/withdrawal_worker_pro.ex:78: field `account_id` in `where` does not exist in schema BacPro.Accounts.Account in query:\n\nfrom a0 in BacPro.Accounts.Account,\n  where: a0.account_id == ^\"060a632d-b977-4190-9b9d-0fc8dd47e7de\",\n  update: [set: [balance: ^1300.0]],\n  select: a0\n\nDid you mean one of: \n\n      * `account_type`\n      * `account_status`\n      * `account_number`\n", __struct__: Ecto.QueryError, __exception__: true]
17:00:01.826 [error] [message: "lib/bac_pro/workers/withdrawal_worker_pro.ex:78: field `account_id` in `where` does not exist in schema BacPro.Accounts.Account in query:\n\nfrom a0 in BacPro.Accounts.Account,\n  where: a0.account_id == ^\"060a632d-b977-4190-9b9d-0fc8dd47e7de\",\n  update: [set: [balance: ^1300.0]],\n  select: a0\n\nDid you mean one of: \n\n      * `account_type`\n      * `account_status`\n      * `account_number`\n", __struct__: Ecto.QueryError, __exception__: true]
17:00:36.026 [error] [term: :ok, __struct__: CaseClauseError, __exception__: true]
17:00:53.107 [error] [term: :ok, __struct__: CaseClauseError, __exception__: true]
17:01:12.198 [error] [term: :ok, __struct__: CaseClauseError, __exception__: true]
16:45:19.769 [error] Customer validator Job id: 25 | Job attempted at: ~U[2024-02-04 16:45:19.755954Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
16:45:19.779 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
16:45:19.774 [error] :gen_event handler {LoggerFileBackend, :debugging_log} installed in Logger terminating
** (UndefinedFunctionError) function Obliviator.Formatter.MessageLog.format/4 is undefined (module Obliviator.Formatter.MessageLog is not available)
    Obliviator.Formatter.MessageLog.format(:debug, "Debugging custmer", {{2024, 2, 4}, {16, 45, 19, 769}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1057.0>, time: 1707065119769082, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}])
    (logger_file_backend 0.0.13) lib/logger_file_backend.ex:87: LoggerFileBackend.log_event/5
    (stdlib 5.1.1) gen_event.erl:802: :gen_event.server_update/4
    (stdlib 5.1.1) gen_event.erl:784: :gen_event.server_notify/4
    (stdlib 5.1.1) gen_event.erl:526: :gen_event.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:debug, #PID<0.645.0>, {Logger, "Debugging custmer", {{2024, 2, 4}, {16, 45, 19, 769}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1057.0>, time: 1707065119769082, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}]}}
State: %{name: :debugging_log, path: "debugging.log", format: {Obliviator.Formatter.MessageLog, :format}, level: :debug, metadata: :all, inode: nil, metadata_filter: [log: :debugging], rotate: nil, io_device: nil}
16:45:19.817 [error] GenServer #PID<0.440.0> terminating
** (stop) {:EXIT, {:undef, [{Obliviator.Formatter.MessageLog, :format, [:debug, "Debugging custmer", {{2024, 2, 4}, {16, 45, 19, 769}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1057.0>, time: 1707065119769082, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}]], []}, {LoggerFileBackend, :log_event, 5, [file: ~c"lib/logger_file_backend.ex", line: 87]}, {:gen_event, :server_update, 4, [file: ~c"gen_event.erl", line: 802]}, {:gen_event, :server_notify, 4, [file: ~c"gen_event.erl", line: 784]}, {:gen_event, :handle_msg, 6, [file: ~c"gen_event.erl", line: 526]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}
Last message: {:gen_event_EXIT, {LoggerFileBackend, :debugging_log}, {:EXIT, {:undef, [{Obliviator.Formatter.MessageLog, :format, [:debug, "Debugging custmer", {{2024, 2, 4}, {16, 45, 19, 769}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1057.0>, time: 1707065119769082, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}]], []}, {LoggerFileBackend, :log_event, 5, [file: ~c"lib/logger_file_backend.ex", line: 87]}, {:gen_event, :server_update, 4, [file: ~c"gen_event.erl", line: 802]}, {:gen_event, :server_notify, 4, [file: ~c"gen_event.erl", line: 784]}, {:gen_event, :handle_msg, 6, [file: ~c"gen_event.erl", line: 526]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}}
State: {LoggerFileBackend, :debugging_log}
16:45:38.401 [error] Customer validator Job id: 25 | Job attempted at: ~U[2024-02-04 16:45:38.393143Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
16:45:38.402 [error] :gen_event handler {LoggerFileBackend, :debugging_log} installed in Logger terminating
** (UndefinedFunctionError) function Obliviator.Formatter.MessageLog.format/4 is undefined (module Obliviator.Formatter.MessageLog is not available)
    Obliviator.Formatter.MessageLog.format(:debug, "Debugging custmer", {{2024, 2, 4}, {16, 45, 38, 401}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1069.0>, time: 1707065138401198, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}])
    (logger_file_backend 0.0.13) lib/logger_file_backend.ex:87: LoggerFileBackend.log_event/5
    (stdlib 5.1.1) gen_event.erl:802: :gen_event.server_update/4
    (stdlib 5.1.1) gen_event.erl:784: :gen_event.server_notify/4
    (stdlib 5.1.1) gen_event.erl:526: :gen_event.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:debug, #PID<0.645.0>, {Logger, "Debugging custmer", {{2024, 2, 4}, {16, 45, 38, 401}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1069.0>, time: 1707065138401198, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}]}}
State: %{name: :debugging_log, path: "debugging.log", format: {Obliviator.Formatter.MessageLog, :format}, level: :debug, metadata: :all, inode: nil, metadata_filter: [log: :debugging], rotate: nil, io_device: nil}
16:45:38.403 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
16:45:38.406 [error] GenServer #PID<0.1063.0> terminating
** (stop) {:EXIT, {:undef, [{Obliviator.Formatter.MessageLog, :format, [:debug, "Debugging custmer", {{2024, 2, 4}, {16, 45, 38, 401}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1069.0>, time: 1707065138401198, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}]], []}, {LoggerFileBackend, :log_event, 5, [file: ~c"lib/logger_file_backend.ex", line: 87]}, {:gen_event, :server_update, 4, [file: ~c"gen_event.erl", line: 802]}, {:gen_event, :server_notify, 4, [file: ~c"gen_event.erl", line: 784]}, {:gen_event, :handle_msg, 6, [file: ~c"gen_event.erl", line: 526]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}
Last message: {:gen_event_EXIT, {LoggerFileBackend, :debugging_log}, {:EXIT, {:undef, [{Obliviator.Formatter.MessageLog, :format, [:debug, "Debugging custmer", {{2024, 2, 4}, {16, 45, 38, 401}}, [erl_level: :debug, function: "process/1", line: 41, module: BacPro.Workers.CustomerValidatorWorkerPro, pid: #PID<0.1069.0>, time: 1707065138401198, log: :debugging, file: "lib/bac_pro/workers/customer_validator_worker_pro.ex", gl: #PID<0.645.0>, domain: [:elixir], application: :bac_pro, mfa: {BacPro.Workers.CustomerValidatorWorkerPro, :process, 1}]], []}, {LoggerFileBackend, :log_event, 5, [file: ~c"lib/logger_file_backend.ex", line: 87]}, {:gen_event, :server_update, 4, [file: ~c"gen_event.erl", line: 802]}, {:gen_event, :server_notify, 4, [file: ~c"gen_event.erl", line: 784]}, {:gen_event, :handle_msg, 6, [file: ~c"gen_event.erl", line: 526]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}}
State: {LoggerFileBackend, :debugging_log}
16:45:39.407 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:45:40.409 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:45:41.411 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:45:42.415 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:50:38.573 [error] Customer validator Job id: 30 | Job attempted at: ~U[2024-02-04 16:50:38.528910Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
16:50:38.605 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
16:50:55.634 [error] Customer validator Job id: 30 | Job attempted at: ~U[2024-02-04 16:50:55.620083Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
16:50:55.637 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
16:50:56.643 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:51:00.699 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:51:01.699 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:51:02.735 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:59:38.382 [error] Customer validator Job id: 35 | Job attempted at: ~U[2024-02-04 16:59:38.370784Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
16:59:38.387 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
16:59:55.855 [error] Customer validator Job id: 35 | Job attempted at: ~U[2024-02-04 16:59:55.849067Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
16:59:55.858 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
16:59:56.866 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:59:57.866 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:59:58.870 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
16:59:59.871 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:57:34.767 [error] Customer validator Job id: 40 | Job attempted at: ~U[2024-02-04 20:57:34.742193Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
20:57:34.841 [error] [Oban.Pro.Worker] hook error: ** (UndefinedFunctionError) function BacPro.Workershook.ErrorHook.after_process/2 is undefined or private
    (bac_pro 0.1.0) BacPro.Workershook.ErrorHook.after_process(:error, %Oban.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">, id: 40, state: "executing", queue: "valid", worker: "BacPro.Workers.CustomerValidatorWorkerPro", args: %{"customer" => %{"dateOfBirth" => "2000-10-22", "email" => "hata1111@gmail.com", "firstname" => "Hataluli", "idNumber" => "5811111121211", "lastname" => "Randima", "phoneNumber" => "727941660"}}, meta: %{"deps" => [], "name" => "a", "workflow_id" => "018d75e9-8483-7f3d-9af2-5f67a21f0224"}, tags: ["customer", "validation"], errors: [], attempt: 1, attempted_by: ["DESKTOP-57HBI13", "018d7507-43da-7a64-8c05-20b329083279"], max_attempts: 2, priority: 3, attempted_at: ~U[2024-02-04 20:57:34.742193Z], cancelled_at: nil, completed_at: nil, discarded_at: nil, inserted_at: ~U[2024-02-04 20:57:34.636688Z], scheduled_at: ~U[2024-02-04 20:57:34.636688Z], conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Engines.Smart, get_dynamic_repo: nil, insert_trigger: true, log: false, name: Oban, node: "DESKTOP-57HBI13", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Pro.Plugins.DynamicQueues, [queues: [default: 10, valid: 12, scheduled: 10, crato: 25, events: 20]]}, {Oban.Pro.Plugins.DynamicPruner, [mode: {:max_age, {2, :days}}]}], prefix: "public", queues: [], repo: BacPro.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, conflict?: false, replace: nil, unique: nil, unsaved_error: %{reason: %Oban.PerformError{message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}}, stacktrace: [], kind: :error}})
    (elixir 1.16.0-rc.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (oban_pro 1.3.3) lib/oban/pro/stages/hooks.ex:68: Oban.Pro.Stages.Hooks.handle_event/4
    (telemetry 1.2.1) /home/hataluli/TauSpace/2024/Bac-Pro/bac_pro/deps/telemetry/src/telemetry.erl:160: anonymous fn/4 in :telemetry.execute/3
    (stdlib 5.1.1) lists.erl:1686: :lists.foreach_1/2
    (oban 2.17.3) lib/oban/queue/executor.ex:266: Oban.Queue.Executor.emit_event/1
    (oban 2.17.3) lib/oban/queue/executor.ex:81: anonymous fn/1 in Oban.Queue.Executor.call/1
    (oban 2.17.3) lib/oban/backoff.ex:104: Oban.Backoff.with_retry/3
    (elixir 1.16.0-rc.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.16.0-rc.0) lib/task/supervised.ex:36: Task.Supervised.reply/4

20:57:42.536 [error] Customer validator Job id: 45 | Job attempted at: ~U[2024-02-04 20:57:42.525955Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
20:57:42.539 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
20:57:51.978 [error] Customer validator Job id: 40 | Job attempted at: ~U[2024-02-04 20:57:51.960912Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
20:57:51.984 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
20:57:52.998 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:57:53.041 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:57:58.016 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:57:59.031 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:58:01.043 [error] Customer validator Job id: 45 | Job attempted at: ~U[2024-02-04 20:58:01.035240Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
20:58:01.047 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
20:58:02.052 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:58:06.089 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:58:07.095 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:59:27.895 [error] Customer validator Job id: 49 | Job attempted at: ~U[2024-02-04 20:59:27.887862Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
20:59:27.902 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
20:59:46.652 [error] Customer validator Job id: 49 | Job attempted at: ~U[2024-02-04 20:59:46.642340Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
20:59:46.673 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
20:59:47.669 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:59:51.682 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:59:52.694 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
20:59:53.701 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
21:00:43.319 [error] Customer validator Job id: 54 | Job attempted at: ~U[2024-02-04 21:00:43.292952Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
21:00:43.339 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
21:01:00.960 [error] Customer validator Job id: 54 | Job attempted at: ~U[2024-02-04 21:01:00.953188Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
21:01:00.963 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
21:01:01.969 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
21:01:06.015 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
21:01:07.012 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
21:01:08.023 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:02:42.153 erl_level=error function=process/1 line=44 module=BacPro.Workers.CustomerValidatorWorkerPro pid=<0.892.0> file=lib/bac_pro/workers/customer_validator_worker_pro.ex domain=elixir application=bac_pro mfa=BacPro.Workers.CustomerValidatorWorkerPro.process/1 [error] Customer validator Job id: 59 | Job attempted at: ~U[2024-02-04 21:02:42.134449Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
23:02:42.170 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.892.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
23:03:00.443 erl_level=error function=process/1 line=44 module=BacPro.Workers.CustomerValidatorWorkerPro pid=<0.900.0> file=lib/bac_pro/workers/customer_validator_worker_pro.ex domain=elixir application=bac_pro mfa=BacPro.Workers.CustomerValidatorWorkerPro.process/1 [error] Customer validator Job id: 59 | Job attempted at: ~U[2024-02-04 21:03:00.431472Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
23:03:00.447 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.900.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
23:03:05.472 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.902.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:03:06.479 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.903.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:03:07.489 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.904.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:03:08.501 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.905.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:10:31.819 erl_level=error function=process/1 line=44 module=BacPro.Workers.CustomerValidatorWorkerPro pid=<0.893.0> file=lib/bac_pro/workers/customer_validator_worker_pro.ex domain=elixir application=bac_pro mfa=BacPro.Workers.CustomerValidatorWorkerPro.process/1 [error] Customer validator Job id: 64 | Job attempted at: ~U[2024-02-04 21:10:31.808386Z]| Job state: "executing" | Job queue: "valid" | Job queue: 1 | Error : Phone number must be 10 digits
23:10:31.826 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.893.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
23:10:49.521 erl_level=error function=process/1 line=44 module=BacPro.Workers.CustomerValidatorWorkerPro pid=<0.933.0> file=lib/bac_pro/workers/customer_validator_worker_pro.ex domain=elixir application=bac_pro mfa=BacPro.Workers.CustomerValidatorWorkerPro.process/1 [error] Customer validator Job id: 64 | Job attempted at: ~U[2024-02-04 21:10:49.515089Z]| Job state: "executing" | Job queue: "valid" | Job queue: 2 | Error : Phone number must be 10 digits
23:10:49.524 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.933.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CustomerValidatorWorkerPro failed with {:error, \"Phone number must be 10 digits\"}", reason: {:error, "Phone number must be 10 digits"}, __struct__: Oban.PerformError, __exception__: true]
23:10:50.528 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.934.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CreateCustomerWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:10:51.529 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.935.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CreateAccountWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:10:52.534 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.936.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.CreateCardWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
23:10:53.535 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.937.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.EmailWorkerPro failed with {:cancel, \"upstream deps cancelled, workflow will never complete\"}", reason: {:cancel, "upstream deps cancelled, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
00:05:43.513 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.1004.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:error, \"Insufficient funds\"}", reason: {:error, "Insufficient funds"}, __struct__: Oban.PerformError, __exception__: true]
00:06:00.701 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.1008.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:error, \"Insufficient funds\"}", reason: {:error, "Insufficient funds"}, __struct__: Oban.PerformError, __exception__: true]
00:06:19.788 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.1011.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:error, \"Insufficient funds\"}", reason: {:error, "Insufficient funds"}, __struct__: Oban.PerformError, __exception__: true]
00:06:42.908 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.1013.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:error, \"Insufficient funds\"}", reason: {:error, "Insufficient funds"}, __struct__: Oban.PerformError, __exception__: true]
00:07:14.064 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.1016.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.WithdrawalWorkerPro failed with {:error, \"Insufficient funds\"}", reason: {:error, "Insufficient funds"}, __struct__: Oban.PerformError, __exception__: true]
00:07:19.088 erl_level=error function=after_process/3 line=12 module=BacPro.Workershook.ErrorHook pid=<0.1017.0> file=lib/bac_pro/workershook/error_hook.ex domain=elixir application=bac_pro mfa=BacPro.Workershook.ErrorHook.after_process/3 [error] [message: "BacPro.Workers.EmailParWorkerPro failed with {:cancel, \"upstream deps discarded, workflow will never complete\"}", reason: {:cancel, "upstream deps discarded, workflow will never complete"}, __struct__: Oban.PerformError, __exception__: true]
